### ISSUE TITLE
Bug with Rey, force token and focus/calculate

### ISSUE THREAD

**Issue by riselin** [punkUser/xwing_math#10]
I noticed this mistake:
Rey pilot + Finn + 1 force + focus has lower expected damage (2.828) than Rey pilot + Finn + 1 force + calculate (3.078) 

http://xwing.gateofstorms.net/2/multi/?d=AAAAAAAAAAAA&a1=MQkAAAwAAAgA
http://xwing.gateofstorms.net/2/multi/?d=AAAAAAAAAAAA&a1=MUEAAAwAAAgA

When going to the How To Modify, Rey does not use the force to turn a blank when a focus is present. But she does turn the blank if with a calculate
http://xwing.gateofstorms.net/2/modify_attack/?a=AAkAAAwAAAAA&r=EQEAAA
http://xwing.gateofstorms.net/2/modify_attack/?a=AEEAAAwAAAAA&r=EQEAAA

**Comment by punkUser** [comment]
Good catch! Will check this out when I get the chance. Thanks for the useful repro steps!
