### ISSUE TITLE
Heroic doesn’t appear to be calculated for attacks

### ISSUE THREAD

**Issue by mflick89** [punkUser/xwing_math#18]
When using the calculator to see what benefit heroic adds on two die attacks with a focus, the calculator is not showing a probability difference to roll 0 hits with or without heroic.
I know.. heroic is a meme, but this was surprising :)

For reference 2 dice + focus:
No heroic - http://xwing.gateofstorms.net/2/multi/?d=AAAAAAAAAAAA&a1=IQgAAAAAAAAA
Heroic - http://xwing.gateofstorms.net/2/multi/?d=AAAAAAAAAAAA&a1=IQgAAAAAACAA

**Comment by punkUser** [comment]
Hmm that definitely looks wrong... something may have broken in the last round of updates.

Thanks for pointing it out, I'll take a look when I get the chance!

**Comment by punkUser** [comment]
Yep definitely is broken, thanks for the report! Fix incoming...

**Comment by mflick89** [comment]
Ty!
