### ISSUE TITLE
Expected Total Hits Clarification

### ISSUE THREAD

**Issue by kellengreen** [punkUser/xwing_math#25]
There is likely something I'm missing, but can I get clarification on how 3 attack with focus vs 2 defense is 1.531 expected hits? I would have expected the result to be 1.50 (2.25 - 0.75). Is direct hit damage potential being added or something?

Thanks,

**Comment by punkUser** [comment]
It's the mean (average) of the distribution of hits that is shown at the bottom when you simulate.

Short answer: you can't simply subtract "average" results from the red and green dice for a variety of reasons. You need to work out the possible outcomes and their associated probabilities (which is what the tool does).

To see an example of why, consider for instance a single red die vs. 2 green dice; by the logic above you would get (0.5 - 0.75) = -0.25 average hits? Even if you clamp to 0 (for some reason) it's clearly wrong that you can't hit the ship; the average should be greater than zero as it's definitely possible to land a hit. (In reality, the average is 0.195: http://xwing.gateofstorms.net/2/multi/?d=AgAAAAAAAAAA&a1=EQAAAAAAAAAA).

If you google around for probability distributions and in particular the binomial distribution and how it applies to dice math you should be able to find lots more info if you are interested.

Hope that helps!

**Comment by kellengreen** [comment]
Thank you.
