### ISSUE TITLE
modelling TLT

### ISSUE THREAD

**Issue by lhayhurst** [punkUser/xwing_math#3]
Hi, is there a way to use the tool to model and Ezra+Maul TLT shot? love the tool, nice work

**Comment by punkUser** [comment]
Yes! Here's a link to Ezra+Maul TLT shot against a 3 agility ship with no tokens:
http://xwing.gateofstorms.net/?q=MQADAAACAQAAAAAEAAAAAA==

Note that you can adjust things if you want to allow Maul to reroll more than one die, but that's the basics. Just set Ezra+Maul crew, "one damage on hit" (TLT effect) and "Secondary Perform Twice" as your attack type.

In advanced, you can do it via the combination of options:
- Lose Stress on Hit (Maul)
- One Damage on Hit (TLT, Ion)
- IF UNSTRESSED, REROLL: Any, Gain Stress (max # you want to allow Maul to reroll)
- IF STRESSED, CHANGE: Focus to Crit (1)
- Secondary Perform Twice

http://xwing.gateofstorms.net/advanced/?q=BAAAAAAAAAAxAAAAAAAAAAADAAAAAAAAABAAAAgAAAAA8QAA

**Comment by lhayhurst** [comment]
Nice! And it looks like I can model Rey with Fenn crew and falcon evade title too, yeah?

**Comment by punkUser** [comment]
Yup, all that is in there. Note that if you enable Finn/Rey you are making those effects active, i.e. assuming the attack is in arc. This is the same with other stuff too (ex. autothrusters) so just pick whatever you want to be active in a given simulation.

For Falcon evade title, just add an evade token or similar.

**Comment by lhayhurst** [comment]
Cool. Purely hypothetical analysis of course :) I will give it a shot when I am back in front of computer!

**Comment by lhayhurst** [comment]
Back on front of computer! Sorry for the n00b question, but looks like Rey is available on the Basic tab, and when I jump between tabs it resets the settings in advanced! Is there a way to get the whole shebang in one go (Maul+Ezra+TLT vs Rey+Evade+C3P0)? something like this is close http://xwing.gateofstorms.net/?q=MAABAQACAAgAAARIAAAAAA== but it doesn't have the IF UNSTRESSED and IF STRESSED reroll stuff (which maybe is built into turning on Ezra and Maul)?

**Comment by punkUser** [comment]
The "advanced" interface is just a different way of accessing the simulation directly: anything that can be done in the "basic" interface can be done in the advanced interface, but the naming in the basic interface is organized more like the upgrade cards and the advanced interface more like the timing chart.

Indeed in the "basic" interface, all the relevant logic is baked into stuff like Ezra and Maul and so on, so there's no need to do the advanced things.

Your link above is doing almost what you want, you just need to set it to a "secondary perform twice" attack and enable "one damage on hit":
http://xwing.gateofstorms.net/?q=MQABAQACAQgAAARIAAAAAA==

That will get you a TLT shot with ezra+maul vs. Rey+Finn+C3P0+an evade in arc.

**Comment by lhayhurst** [comment]
cool! great work again. closing ticket out. cheers
