### ISSUE TITLE
Request: Add Saturation Salvo to 2.0 Calculator

### ISSUE THREAD

**Issue by kyledsimpson** [punkUser/xwing_math#5]
Really love the site - thanks for creating it!  
Unless there's a way to calculate this already (force defender to reroll 2 dice), I would like to see this talent added http://xwing-miniatures-second-edition.wikia.com/wiki/Saturation_Salvo

**Comment by punkUser** [comment]
Thanks!

Saturation Salvo is indeed not yet added to the calculator. It has a bit of a weird interaction in that you must choose two dice (can't choose one, presumably unless there only is one dice that can be rerolled). It's on the TODO list though and I'll bump it up in priority per your request.
