### ISSUE TITLE
[Feature Request] Display results in a table based on attacker's and defender's dice mods

### ISSUE THREAD

**Issue by bluerook17** [punkUser/xwing_math#7]
Hi! I'm building an efficiency spreadsheet for X-Wing 2.0. I've been using your calculator to build attack/agility tables, which currently requires a lot of time and copy-pasting. Would it be possible to add a feature to your calculator to output a table in this format?

![attack tables](https://user-images.githubusercontent.com/27330883/47620682-47083c00-dac3-11e8-8b35-70701d176824.png)

Thanks so much! Your calculator has been a big help for me, and my efficiency spreadsheet wouldn't be possible without this.

**Comment by bluerook17** [comment]
Quick note about the tables in the screenshots. The blended numbers are averages based on meta assumptions, so the output probably won't need those rows/columns. Agility should probably go up to 5 for obstructed shots, while I don't think attack values naturally go above 5.

**Comment by bluerook17** [comment]
If possible, I'd also really appreciate being able to display the probability of keeping a defense token after 1 attack in this tabular form as well.

**Comment by punkUser** [comment]
Thanks for the interest! Unfortunately this kind of feature to convert output to a specific format is not the sort of thing that we implement in the main calculator repo.

That said, this is _exactly_ the sort of reason the project is open source :) It's pretty easy to script the calculator to do whatever simulations and dump whatever output you want. Take a look at the code that drives the simulation in [regression_tests.d](https://github.com/punkUser/xwing_math/blob/master/source/regression_tests.d) for instance. That code can be easily modified to run whatever simulations you want and dump the output to a CSV or whatever format is convenient.

Alternatively the core simulation is invoked via a simple JSON query/API. While it isn't documented in detail anywhere it's pretty simple and you should be able to call it directly by taking a look at how the webform submission works. An extra step over just calling the simulation direction via D, but if you're more familiar with that sort of thing, etc.

Thanks again for your interest and let me know if I can point you at anything in terms of doing the scripting for your purposes.
